### ISSUE TITLE
Losing modal button should not display text next level. 

### ISSUE THREAD

**Issue by TayKangSheng** [wdi-sg/wdi-project-1-skeerti2#6]
After the game has ended without the player catching more than 2 puppies, the following modal appears. 

"You caught 0 out of 9 puppies, you need to catch more than 2. Please Restart"

The button to close the modal has the text "Next Level" which should not be the case. You should prompt the user to restart the game here.

**Comment by skeerti2** [comment]
Fixed :) Now it shows "Press Restart Button"
